apiVersion: v1
kind: Service
metadata:
  name: {{ include "distributed-systems-showcase.fullname" . }}-app
  labels:
    {{- include "distributed-systems-showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "distributed-systems-showcase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
